### ISSUE TITLE
Using in View

### ISSUE THREAD

**Issue by slawder** [Myagi/react-native-wistia#3]
Can this component be called in a View like this ?

```
        <View style={{height:200}}>
          <Text style={styles.course_title}>{lesson.fields.title}</Text>
					<Wistia
					    ref='video'
					    videoId={lesson.video} // Wistia video ID
					    onReady={ () => console.log('Video is ready') }
					    onPlay={ () => console.log('Video is playing') }
					    onEnd={ () => console.log('Video is finished') }
					  />
        </View>
```

Getting a error on that that it was expecting a string, but returned undefined. 

It also may be that I'm not importing the component in correctly. Only way I can get it to load without crashing is in the array loading from 'react-native'. Doing something like this doesn't work as I would expect it would : 

`import Wistia from 'react-native-wistia'
`

Any suggestions?

**Comment by alex-mcleod** [comment]
@slawder what version of React Native are you using?

**Comment by slawder** [comment]
Thanks Alex - 0.33.0

**Comment by slawder** [comment]
Looks like NPM was just installing an older 'version' of the script. Manually plugging the current code in got things corrected, at least from erroring. 

No errors now, but video never loads, just is blank. The WebViewBridge content is loading fine (I can edit those contents and validate that) but the embed script doesn't execute. Works fine in standard desktop browser.  Anything else I could be missing?

**Comment by slawder** [comment]
Was able to get it to work locally by enabling this setting : http://stackoverflow.com/questions/38077273/react-native-fetch-network-request-failed-not-using-localhost

And then forcing https for the script load call in the player-html.js . Seems like a workaround for now. Any suggestions for avoiding that?

**Comment by alex-mcleod** [comment]
@slawder no suggestions right now unfortunately. Have yet to come up against the same issue, though we are using a slightly older version of React Native which might be why. 

Also, the code here on Github is more up to date then what is on NPM, so I'll update the library there as well. In future, rather than copying the code directly from Github, you can actually install directly from Github using npm like so: `npm install github:Myagi/react-native-wistia#master`. You can also replace the `#master` with a commit hash to target a specific commit.
